apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tec4-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: tec4-ip
  labels:
    app: hello
spec:
  backend:
    serviceName: tec4-backend
    servicePort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: tec4-backend
  labels:
    app: tec4
spec:
  type: NodePort
  selector:
    app: tec4
    tier: web
  ports:
  - port: 8000
    targetPort: 8000