# Generated by Django 3.0.2 on 2020-01-25 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('hospitalAgree', models.BooleanField()),
                ('municipalityAgree', models.BooleanField()),
                ('supplierAgree', models.BooleanField()),
                ('hospitalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthcare.Hospital')),
                ('municipalityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthcare.Municipality')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthcare.Patient')),
                ('supplierId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthcare.Supplier')),
            ],
        ),
    ]
